---
# tasks file for apache2
- name: install apache2
  ansible.builtin.apt:
    name: apache2
    state: present

- name: copy the file
  ansible.builtin.copy:
    src: index.html
    dest: /var/www/html

